CREATE TABLE AUTHORS(
AUTH_ID INT PRIMARY KEY,
AUTH_NAME VARCHAR(50),
COUNTRY VARCHAR(100));

CREATE TABLE BOOKS(
BOOK_ID INT PRIMARY KEY,
BOOK_NAME VARCHAR(50),
AUTH_ID INT,
PUBLISH_YEAR INT);

ALTER TABLE BOOKS
ADD CONSTRAINT fk_books_authors
FOREIGN KEY (AUTH_ID) REFERENCES AUTHORS(AUTH_ID);

INSERT INTO AUTHORS (AUTH_ID,AUTH_NAME,COUNTRY) VALUES
(1,'JAYESH SAINI','INDIA'),
(2,'DEVANSH SINGH','UNITED STATES'),
(3,'ADITYA SINGH RATHAUR','UNITED KINGDOM');

INSERT INTO BOOKS (BOOK_ID,BOOK_NAME,AUTH_ID,PUBLISH_YEAR) VALUES
(1001,'DSFBFDSDF',1,2021),
(1002,'FDFFH',2,2021),
(1003,'IDHCG',1,2021),
(1004,'DKJSVHBDKJ',1,2021),
(1005,'DHVYUUABS ICHUSIDBCJ',3,2021),
(1006,'CHDG',3,2021),
(1007,'BDC FGHD',2,2021);

SELECT B.BOOK_ID,B.BOOK_NAME,B.PUBLISH_YEAR,A.AUTH_NAME,A.COUNTRY FROM
AUTHORS A INNER JOIN BOOKS B ON
A.AUTH_ID = B.AUTH_ID;
